; pause.g
; called when a print from SD card is paused
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Mon Jul 19 2021 19:28:32 GMT-0400 (Eastern Daylight Time)
M83            ; relative extruder moves
G1 E-10 F3600  ; retract 10mm of filament
G91            ; relative positioning
G1 Z5 F360     ; lift Z by 5mm
G90            ; absolute positioning
G1 X{move.axes[0].min + 20} Y{move.axes[1].max - 20} F6000 ; go to X=0 Y=0

